import java.sql.*;
import javax.swing.ButtonGroup;
import static javax.swing.JOptionPane.showMessageDialog;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Felix
 */
public class EditReminderPemasukan extends javax.swing.JFrame {
    private int idReminderPemasukan;
    private String jenisReminder;
    private String hariTanggal;
    private String keterangan;
    private String statusEnabled;
    TampilkanReminder formReminder;
    /**
     * Creates new form TambahReminderPemasukan
     */
    public EditReminderPemasukan(TampilkanReminder formReminder,int idReminderPemasukan,String jenisReminder,String hariTanggal,String keterangan,String statusEnabled) {
        initComponents();
        this.formReminder=formReminder;
        this.idReminderPemasukan=idReminderPemasukan;
        this.jenisReminder=jenisReminder;
        this.hariTanggal=hariTanggal;
        this.keterangan=keterangan;
        this.statusEnabled=statusEnabled;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        rbMingguan = new javax.swing.JRadioButton();
        rbBulanan = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        cbHari = new javax.swing.JComboBox();
        cbTanggal = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tfKeterangan = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cbEnabled = new javax.swing.JCheckBox();
        btnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Jenis reminder:");

        rbMingguan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbMingguan.setText("Mingguan");
        rbMingguan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMingguanActionPerformed(evt);
            }
        });

        rbBulanan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbBulanan.setText("Bulanan");
        rbBulanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBulananActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Hari:");

        cbHari.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu", "Minggu" }));

        cbTanggal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Tanggal:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Keterangan:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Enabled:");

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbEnabled)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbMingguan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbBulanan)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOK)
                .addGap(166, 166, 166))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rbMingguan)
                    .addComponent(rbBulanan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tfKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel16))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbEnabled)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(btnOK)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbMingguanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMingguanActionPerformed
        cbHari.setEnabled(true);
        cbTanggal.setEnabled(false);
    }//GEN-LAST:event_rbMingguanActionPerformed

    private void rbBulananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBulananActionPerformed
        cbHari.setEnabled(false);
        cbTanggal.setEnabled(true);
    }//GEN-LAST:event_rbBulananActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        String keterangan=tfKeterangan.getText();
        int enabled;
        if(cbEnabled.isSelected())
            enabled=1;
        else
            enabled=0;
        String sql;
        if(!keterangan.isEmpty()){
            if(rbMingguan.isSelected()){
                int idHari=cbHari.getSelectedIndex()+1;
                sql="UPDATE reminder_pemasukan SET id_kategori_reminder=2,id_hari="+idHari+",keterangan='"+keterangan+"',enabled="+enabled+" WHERE id_reminder_pemasukan="+idReminderPemasukan;
                try{
                    Connection con=ModuleDB.connectDB();
                    Statement stmt=con.createStatement();
                    stmt.executeUpdate(sql);
                    con.close();
                    showMessageDialog(null,"Reminder berhasil diupdate!");
                }
                catch(SQLException e){
                    showMessageDialog(null,e.getMessage());
                }
            }
            else if(rbBulanan.isSelected()){
                int tanggal=Integer.parseInt(cbTanggal.getSelectedItem().toString());
                sql="UPDATE reminder_pemasukan SET id_kategori_reminder=3,tanggal="+tanggal+",keterangan='"+keterangan+"',enabled="+enabled+" WHERE id_reminder_pemasukan="+idReminderPemasukan;
                try{
                    Connection con=ModuleDB.connectDB();
                    Statement stmt=con.createStatement();
                    stmt.executeUpdate(sql);
                    con.close();
                    showMessageDialog(null,"Reminder berhasil diupdate!");
                }
                catch(SQLException e){
                    showMessageDialog(null,e.getMessage());
                }
            }
            formReminder.loadReminderPemasukan(null,1);
        }
        else
            showMessageDialog(null,"Keterangan harus diisi!");
    }//GEN-LAST:event_btnOKActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setLocationRelativeTo(null);
        ButtonGroup grupRBJenisReminder=new ButtonGroup();
        grupRBJenisReminder.add(rbMingguan);
        grupRBJenisReminder.add(rbBulanan);
        if(jenisReminder.equals("mingguan")){
            rbMingguan.setSelected(true);
            cbTanggal.setEnabled(false);
            if(hariTanggal.equals("Senin"))
                cbHari.setSelectedItem("Senin");
            else if(hariTanggal.equals("Selasa"))
                cbHari.setSelectedItem("Selasa");
            else if(hariTanggal.equals("Rabu"))
                cbHari.setSelectedItem("Rabu");
            else if(hariTanggal.equals("Kamis"))
                cbHari.setSelectedItem("Kamis");
            else if(hariTanggal.equals("Jumat"))
                cbHari.setSelectedItem("Jumat");
            else if(hariTanggal.equals("Sabtu"))
                cbHari.setSelectedItem("Sabtu");
            else if(hariTanggal.equals("Minggu"))
                cbHari.setSelectedItem("Minggu");
        }
        else if(jenisReminder.equals("bulanan")){
            rbBulanan.setSelected(true);
            cbHari.setEnabled(false);
            cbTanggal.setSelectedItem(hariTanggal);
        }
        tfKeterangan.setText(keterangan);
        if(statusEnabled=="Yes")
            cbEnabled.setSelected(true);
        else if(statusEnabled=="No")
            cbEnabled.setSelected(false);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahReminderPemasukan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahReminderPemasukan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahReminderPemasukan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahReminderPemasukan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahReminderPemasukan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JCheckBox cbEnabled;
    private javax.swing.JComboBox cbHari;
    private javax.swing.JComboBox cbTanggal;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton rbBulanan;
    private javax.swing.JRadioButton rbMingguan;
    private javax.swing.JTextField tfKeterangan;
    // End of variables declaration//GEN-END:variables
}
