import java.sql.*;
import javax.swing.*;
import static javax.swing.JOptionPane.showMessageDialog;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Felix
 */
public class TambahReminderPengeluaran extends javax.swing.JFrame {
    private ComboBoxModel februariNonKabisat_a=new DefaultComboBoxModel(new String[]{"01","02","03","04","05","06","07","08","09","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28"});
    private ComboBoxModel februariKabisat_a=new DefaultComboBoxModel(new String[]{"01","02","03","04","05","06","07","08","09","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29"});
    private ComboBoxModel bln30hari_a=new DefaultComboBoxModel(new String[]{"01","02","03","04","05","06","07","08","09","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30"});
    private ComboBoxModel bln31hari_a=new DefaultComboBoxModel(new String[]{"01","02","03","04","05","06","07","08","09","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31"});
    private ComboBoxModel februariNonKabisat_b=new DefaultComboBoxModel(new String[]{"01","02","03","04","05","06","07","08","09","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28"});
    private ComboBoxModel februariKabisat_b=new DefaultComboBoxModel(new String[]{"01","02","03","04","05","06","07","08","09","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29"});
    private ComboBoxModel bln30hari_b=new DefaultComboBoxModel(new String[]{"01","02","03","04","05","06","07","08","09","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30"});
    private ComboBoxModel bln31hari_b=new DefaultComboBoxModel(new String[]{"01","02","03","04","05","06","07","08","09","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31"});
    /**
     * Creates new form TambahReminderPengeluaran
     */
    public TambahReminderPengeluaran() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        rbSekaliSaja = new javax.swing.JRadioButton();
        rbMingguan = new javax.swing.JRadioButton();
        rbBulanan = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        cbTanggalIngatkan = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cbBulanIngatkan = new javax.swing.JComboBox();
        cbTahunIngatkan = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbHariIngatkan = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        cbHariDeadline = new javax.swing.JComboBox();
        cbTanggalDeadline = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        cbBulanDeadline = new javax.swing.JComboBox();
        cbTahunDeadline = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tfKeterangan = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cbEnabled = new javax.swing.JCheckBox();
        btnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Jenis reminder:");

        rbSekaliSaja.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbSekaliSaja.setText("Sekali saja");
        rbSekaliSaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSekaliSajaActionPerformed(evt);
            }
        });

        rbMingguan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbMingguan.setText("Mingguan");
        rbMingguan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMingguanActionPerformed(evt);
            }
        });

        rbBulanan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbBulanan.setText("Bulanan");
        rbBulanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBulananActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Ingatkan mulai:");

        cbTanggalIngatkan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Tanggal:");

        cbBulanIngatkan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        cbBulanIngatkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBulanIngatkanActionPerformed(evt);
            }
        });

        cbTahunIngatkan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2025", "2026", "2027", "2028", "2029", "2030" }));
        cbTahunIngatkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTahunIngatkanActionPerformed(evt);
            }
        });

        jLabel6.setText("DD");

        jLabel8.setText("MM");

        jLabel9.setText("YYYY");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Hari:");

        cbHariIngatkan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu", "Minggu" }));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Deadline:");

        cbHariDeadline.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu", "Minggu" }));

        cbTanggalDeadline.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Tanggal:");

        cbBulanDeadline.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        cbBulanDeadline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBulanDeadlineActionPerformed(evt);
            }
        });

        cbTahunDeadline.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2025", "2026", "2027", "2028", "2029", "2030" }));
        cbTahunDeadline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTahunDeadlineActionPerformed(evt);
            }
        });

        jLabel11.setText("DD");

        jLabel12.setText("MM");

        jLabel13.setText("YYYY");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Hari:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Keterangan:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Enabled:");

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbHariIngatkan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbTanggalIngatkan, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)
                                        .addGap(19, 19, 19)
                                        .addComponent(cbBulanIngatkan, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8)
                                        .addGap(13, 13, 13)
                                        .addComponent(cbTahunIngatkan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel14))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbHariDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbTanggalDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel11)
                                                .addGap(19, 19, 19)
                                                .addComponent(cbBulanDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel12)
                                                .addGap(18, 18, 18)
                                                .addComponent(cbTahunDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbSekaliSaja)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbMingguan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbBulanan))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbEnabled)
                                    .addComponent(tfKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(btnOK)))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rbSekaliSaja)
                    .addComponent(rbMingguan)
                    .addComponent(rbBulanan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(cbBulanIngatkan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTanggalIngatkan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTahunIngatkan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbHariIngatkan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11)
                    .addComponent(cbBulanDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTanggalDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(cbTahunDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbHariDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tfKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel16))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbEnabled)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(btnOK)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbSekaliSajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSekaliSajaActionPerformed
        cbTanggalIngatkan.setEnabled(true);
        cbBulanIngatkan.setEnabled(true);
        cbTahunIngatkan.setEnabled(true);
        cbTanggalDeadline.setEnabled(true);
        cbBulanDeadline.setEnabled(true);
        cbTahunDeadline.setEnabled(true);
        cbHariIngatkan.setEnabled(false);
        cbHariDeadline.setEnabled(false);
    }//GEN-LAST:event_rbSekaliSajaActionPerformed

    private void rbMingguanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMingguanActionPerformed
        cbTanggalIngatkan.setEnabled(false);
        cbBulanIngatkan.setEnabled(false);
        cbTahunIngatkan.setEnabled(false);
        cbTanggalDeadline.setEnabled(false);
        cbBulanDeadline.setEnabled(false);
        cbTahunDeadline.setEnabled(false);
        cbHariIngatkan.setEnabled(true);
        cbHariDeadline.setEnabled(true);
    }//GEN-LAST:event_rbMingguanActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setLocationRelativeTo(null);
        ButtonGroup grupRBJenisReminder=new ButtonGroup();
        grupRBJenisReminder.add(rbSekaliSaja);
        grupRBJenisReminder.add(rbMingguan);
        grupRBJenisReminder.add(rbBulanan);
        rbSekaliSaja.setSelected(true);
        cbHariIngatkan.setEnabled(false);
        cbHariDeadline.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void rbBulananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBulananActionPerformed
        cbTanggalIngatkan.setEnabled(true);
        cbBulanIngatkan.setEnabled(false);
        cbTahunIngatkan.setEnabled(false);
        cbTanggalDeadline.setEnabled(true);
        cbBulanDeadline.setEnabled(false);
        cbTahunDeadline.setEnabled(false);
        cbHariIngatkan.setEnabled(false);
        cbHariDeadline.setEnabled(false);
    }//GEN-LAST:event_rbBulananActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        String keterangan=tfKeterangan.getText();
        int enabled;
        if(cbEnabled.isSelected())
            enabled=1;
        else
            enabled=0;
        String sql;
        if(rbSekaliSaja.isSelected()){
            String tanggalIngatkan=cbTanggalIngatkan.getSelectedItem().toString();
            String bulanIngatkan=cbBulanIngatkan.getSelectedItem().toString();
            String tahunIngatkan=cbTahunIngatkan.getSelectedItem().toString();
            String tanggalDeadline=cbTanggalDeadline.getSelectedItem().toString();
            String bulanDeadline=cbBulanDeadline.getSelectedItem().toString();
            String tahunDeadline=cbTahunDeadline.getSelectedItem().toString();
            String tanggalIngatkanLengkap=tahunIngatkan+"-"+bulanIngatkan+"-"+tanggalIngatkan;
            String tanggalDeadlineLengkap=tahunDeadline+"-"+bulanDeadline+"-"+tanggalDeadline;
            int tanggalIngatkanInt=Integer.parseInt(tanggalIngatkan);
            int bulanIngatkanInt=Integer.parseInt(bulanIngatkan);
            int tahunIngatkanInt=Integer.parseInt(tahunIngatkan);
            int tanggalDeadlineInt=Integer.parseInt(tanggalDeadline);
            int bulanDeadlineInt=Integer.parseInt(bulanDeadline);
            int tahunDeadlineInt=Integer.parseInt(tahunDeadline);
            int test=Integer.parseInt(tahunDeadline);
            sql="INSERT INTO reminder_pengeluaran (id_user,id_kategori_reminder,tanggal_notifikasi_sekali,tanggal_deadline_sekali,keterangan,enabled) VALUES ("+ModuleDB.idUser+",1,'"+tanggalIngatkanLengkap+"','"+tanggalDeadlineLengkap+"','"+keterangan+"',"+enabled+");";
            if(!keterangan.isEmpty()){
                if(tahunDeadlineInt>tahunIngatkanInt || (tahunDeadlineInt==tahunIngatkanInt && (bulanDeadlineInt>bulanIngatkanInt || (bulanDeadlineInt==bulanIngatkanInt && tanggalDeadlineInt>=tanggalIngatkanInt)))){
                    try{
                        Connection con=ModuleDB.connectDB();
                        Statement stmt=con.createStatement();
                        stmt.executeUpdate(sql);
                        con.close();
                        showMessageDialog(null,"Reminder pengeluaran berhasil disimpan!");
                    }
                    catch(SQLException e){
                        showMessageDialog(null,e.getMessage());
                    }
                }
                else
                    showMessageDialog(null,"Tanggal mulai ingatkan harus berada sebelum tanggal deadline!");
            }
            else
                showMessageDialog(null,"Keterangan harus diisi!");
        }
        else if(rbMingguan.isSelected()){
            int idHariIngatkan=cbHariIngatkan.getSelectedIndex()+1;
            int idHariDeadline=cbHariDeadline.getSelectedIndex()+1;
            sql="INSERT INTO reminder_pengeluaran (id_user,id_kategori_reminder,id_hari_notifikasi_mingguan,id_hari_deadline_mingguan,keterangan,enabled) VALUES ("+ModuleDB.idUser+",2,"+idHariIngatkan+","+idHariDeadline+",'"+keterangan+"',"+enabled+");";
            if(!keterangan.isEmpty()){
                try{
                    Connection con=ModuleDB.connectDB();
                    Statement stmt=con.createStatement();
                    stmt.executeUpdate(sql);
                    con.close();
                    showMessageDialog(null,"Reminder pengeluaran berhasil disimpan!");
                }
                catch(SQLException e){
                    showMessageDialog(null,e.getMessage());
                }
            }
            else
                showMessageDialog(null,"Keterangan harus diisi!");
        }
        else if(rbBulanan.isSelected()){
            String tanggalIngatkan=cbTanggalIngatkan.getSelectedItem().toString();
            String tanggalDeadline=cbTanggalDeadline.getSelectedItem().toString();
            sql="INSERT INTO reminder_pengeluaran (id_user,id_kategori_reminder,tanggal_notifikasi_bulanan,tanggal_deadline_bulanan,keterangan,enabled) VALUES ("+ModuleDB.idUser+",3,"+tanggalIngatkan+","+tanggalDeadline+",'"+keterangan+"',"+enabled+");";
            if(!keterangan.isEmpty()){
                try{
                    Connection con=ModuleDB.connectDB();
                    Statement stmt=con.createStatement();
                    stmt.executeUpdate(sql);
                    con.close();
                    showMessageDialog(null,"Reminder pengeluaran berhasil disimpan!");
                }
                catch(SQLException e){
                    showMessageDialog(null,e.getMessage());
                }
            }
            else
                showMessageDialog(null,"Keterangan harus diisi!");
        }
    }//GEN-LAST:event_btnOKActionPerformed

    private void cbBulanIngatkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBulanIngatkanActionPerformed
        int bulanIngatkan=cbBulanIngatkan.getSelectedIndex()+1;
        int tahunIngatkan=Integer.parseInt(cbTahunIngatkan.getSelectedItem().toString());
        if(bulanIngatkan<=7 && bulanIngatkan%2!=0 || bulanIngatkan>=8 && bulanIngatkan%2==0)
            cbTanggalIngatkan.setModel(bln31hari_a);
        else if(bulanIngatkan<=7 && bulanIngatkan%2==0 && bulanIngatkan!=2 || bulanIngatkan>=8 && bulanIngatkan%2!=0)
            cbTanggalIngatkan.setModel(bln30hari_a);
        else if(bulanIngatkan==2 && tahunIngatkan%4!=0)
            cbTanggalIngatkan.setModel(februariNonKabisat_a);
        else if(bulanIngatkan==2 && tahunIngatkan%4==0)
            cbTanggalIngatkan.setModel(februariKabisat_a);
    }//GEN-LAST:event_cbBulanIngatkanActionPerformed

    private void cbBulanDeadlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBulanDeadlineActionPerformed
        int bulanDeadline=cbBulanDeadline.getSelectedIndex()+1;
        int tahunDeadline=Integer.parseInt(cbTahunDeadline.getSelectedItem().toString());
        if(bulanDeadline<=7 && bulanDeadline%2!=0 || bulanDeadline>=8 && bulanDeadline%2==0)
            cbTanggalDeadline.setModel(bln31hari_b);
        else if(bulanDeadline<=7 && bulanDeadline%2==0 && bulanDeadline!=2 || bulanDeadline>=8 && bulanDeadline%2!=0)
            cbTanggalDeadline.setModel(bln30hari_b);
        else if(bulanDeadline==2 && tahunDeadline%4!=0)
            cbTanggalDeadline.setModel(februariNonKabisat_b);
        else if(bulanDeadline==2 && tahunDeadline%4==0)
            cbTanggalDeadline.setModel(februariKabisat_b);
    }//GEN-LAST:event_cbBulanDeadlineActionPerformed

    private void cbTahunIngatkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTahunIngatkanActionPerformed
        int bulanIngatkan=cbBulanIngatkan.getSelectedIndex()+1;
        int tahunIngatkan=Integer.parseInt(cbTahunIngatkan.getSelectedItem().toString());
        if(bulanIngatkan==2 && tahunIngatkan%4!=0)
            cbTanggalIngatkan.setModel(februariNonKabisat_a);
        else if(bulanIngatkan==2 && tahunIngatkan%4==0)
            cbTanggalIngatkan.setModel(februariKabisat_a);
    }//GEN-LAST:event_cbTahunIngatkanActionPerformed

    private void cbTahunDeadlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTahunDeadlineActionPerformed
        int bulanDeadline=cbBulanDeadline.getSelectedIndex()+1;
        int tahunDeadline=Integer.parseInt(cbTahunDeadline.getSelectedItem().toString());
        if(bulanDeadline==2 && tahunDeadline%4!=0)
            cbTanggalDeadline.setModel(februariNonKabisat_b);
        else if(bulanDeadline==2 && tahunDeadline%4==0)
            cbTanggalDeadline.setModel(februariKabisat_b);
    }//GEN-LAST:event_cbTahunDeadlineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahReminderPengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahReminderPengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahReminderPengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahReminderPengeluaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahReminderPengeluaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JComboBox cbBulanDeadline;
    private javax.swing.JComboBox cbBulanIngatkan;
    private javax.swing.JCheckBox cbEnabled;
    private javax.swing.JComboBox cbHariDeadline;
    private javax.swing.JComboBox cbHariIngatkan;
    private javax.swing.JComboBox cbTahunDeadline;
    private javax.swing.JComboBox cbTahunIngatkan;
    private javax.swing.JComboBox cbTanggalDeadline;
    private javax.swing.JComboBox cbTanggalIngatkan;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rbBulanan;
    private javax.swing.JRadioButton rbMingguan;
    private javax.swing.JRadioButton rbSekaliSaja;
    private javax.swing.JTextField tfKeterangan;
    // End of variables declaration//GEN-END:variables
}
